# Copyright      2021  Xiaomi Corp.       (author: Fangjun Kuang)

# See ../../LICENSE for clarification regarding multiple authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# refer to https://github.com/actions/starter-workflows/pull/47/files

name: build_conda_ubuntu

on:
  push:
    branches:
      - manual
    tags:
      - '*'
    paths:
      - '.github/workflows/build_conda_ubuntu.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'scripts/build_conda.sh'
      - 'scripts/conda/**'
      - 'kaldifst/csrc/**'
      - 'kaldifst/python/**'
      - 'setup.py'

concurrency:
  group: build_conda_ubuntu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_conda_ubuntu:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
      # refer to https://github.com/actions/checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: kaldifst

      - name: Display Python version
        shell: bash -l {0}
        run: |
          python3 -c "import sys; print(sys.version)"
          which python3

      - name: Install conda dependencies
        shell: bash -l {0}
        run: |
          conda install -y -q anaconda-client
          conda install -y -q conda-build

      - name: Display conda info
        shell: bash -l {0}
        run: |
          which conda
          conda env list
          conda info
          nproc

      - name: Build kaldifst
        shell: bash -l {0}
        env:
          KALDIFST_CONDA_TOKEN: ${{ secrets.KALDIFST_CONDA_TOKEN }}
        run: |
          ./scripts/build_conda.sh

      - name: Display generated files
        run: |
          ls -lh /usr/share/miniconda/envs/kaldifst/conda-bld/linux-64

      - name: Upload generated files
        uses: actions/upload-artifact@v2
        with:
          name: python-${{ matrix.python-version }}-${{ matrix.os }}
          path: /usr/share/miniconda/envs/kaldifst/conda-bld/linux-64/*.tar.bz2
